package spilehx.core.projectsetup;

import haxe.io.Path;
import sys.io.File;
import spilehx.core.filesystem.FileFolderUtils;

@:dox(hide)
class ProjectConfigEntry {
	@:isVar public var file(default, null):String;
	@:isVar public var sectionHeader(default, null):String;
	@:isVar public var content(default, null):String;

	private function new(file:String, sectionHeader:String, content:String) {
		this.file = file;
		this.sectionHeader = sectionHeader;
		this.content = content;
	}

	public static function createGitIgnoreEntry(content:String, ?basePath:String = "."):Void {
		var entry = new ProjectConfigEntryGitIgnore(content);
		addEntry(entry, basePath);
	}

	public static function createImportEntry(content:String, ?basePath:String = "."):Void {
		var entry = new ProjectConfigEntryImport(content);
		addEntry(entry, basePath);
	}

	public static function createBuildHxmlEntry(content:String, ?basePath:String = "."):Void {
		var entry = new ProjectConfigEntryBuildHxml(content);
		addEntry(entry, basePath);
	}

	private static function addEntry(entry:ProjectConfigEntry, basePath:String):Void {
		var validatedPath = Path.normalize(Path.join([basePath, entry.file]));
		FileFolderUtils.ensureFile(validatedPath);

		var currentContent:String = File.getContent(validatedPath);

		var hasHeader = false;
		var hasEntry = false;

		for (line in currentContent.split("\n")) {
			var trimmedLine = StringTools.rtrim(line);

			if (trimmedLine == entry.sectionHeader) {
				hasHeader = true;
			}

			if (trimmedLine == entry.content) {
				hasEntry = true;
			}
		}

		if (hasHeader && hasEntry) {
			return;
		}

		var updatedContent = currentContent;

		if (!hasHeader) {
			var separator = updatedContent.length == 0 || StringTools.endsWith(updatedContent, "\n") ? "" : "\n";

			updatedContent += separator + entry.sectionHeader + "\n";
		}

		if (!hasEntry) {
			var separator = updatedContent.length == 0 || StringTools.endsWith(updatedContent, "\n") ? "" : "\n";

			updatedContent += separator + entry.content + "\n";
		}

		File.saveContent(validatedPath, updatedContent);
	}
}

private class ProjectConfigEntryGitIgnore extends ProjectConfigEntry {
	private static inline var HEADER:String = "# Auto generated by Spilehx";
	private static inline var FILE:String = ".gitignore";

	public function new(content:String) {
		super(FILE, HEADER, content);
	}
}

private class ProjectConfigEntryImport extends ProjectConfigEntry {
	private static inline var HEADER:String = "// Auto generated by Spilehx";
	private static inline var FILE:String = "import.hx";

	public function new(content:String) {
		super(FILE, HEADER, content);
	}
}

private class ProjectConfigEntryBuildHxml extends ProjectConfigEntry {
	private static inline var HEADER:String = "# Auto generated by Spilehx";
	private static inline var FILE:String = "build.hxml";

	public function new(content:String) {
		super(FILE, HEADER, content);
	}
}
