package spilehx.core.macrotools;

import sys.io.File;
import haxe.macro.Context;
import sys.FileSystem;
import haxe.io.Path;

class MacroTools {
	#if macro
	public static function getEnvVar(varName:String):Dynamic {
		var envVar = Context.definedValue(varName);
		if (envVar == null) {
			Context.error("Environment variable " + varName + " not set in .hxml file", Context.currentPos());
		}
		return envVar;
	}

	public static function ensureProjectFolder(path:String):Void {
		Sys.println("Ensuring project folder: " + path);
		var validatedLocalFolderPath:String = validateProjectPath(path);

		if (!FileSystem.exists(validatedLocalFolderPath)) {
			try {
				FileSystem.createDirectory(validatedLocalFolderPath);
			} catch (e:Dynamic) {
				Context.error("Failed to create directory '" + validatedLocalFolderPath + "': " + Std.string(e), Context.currentPos());
			}
		}else {
            Sys.println("Project folder already exists: " + validatedLocalFolderPath);
        }
	}

    public static function ensureProjectFile(filePath:String):Void {
        Sys.println("Ensuring project file: " + filePath);
        var validatedLocalFilePath:String = validateProjectPath(filePath);

        if (!FileSystem.exists(validatedLocalFilePath)) {
            try {
                File.saveContent(validatedLocalFilePath, "");
            } catch (e:Dynamic) {
                Context.error("Failed to create file '" + validatedLocalFilePath + "': " + Std.string(e), Context.currentPos());
            }
        }else {
            Sys.println("Project file already exists: " + validatedLocalFilePath);
        }
    }

	public static function validateProjectPath(path:String):String {
		var root = Path.removeTrailingSlashes(Path.normalize(Sys.getCwd()));
		var resolved = Path.normalize(Path.isAbsolute(path) ? path : Path.join([root, path]));

		if (resolved != root && !StringTools.startsWith(resolved, root + "/")) {
			Context.error("Invalid project path: " + path, Context.currentPos());
		}

		var relative = resolved.substr(root.length);

		return relative == "" ? "." : "." + relative;
	}

    public static function ensureGitIgnoreEntry(path:String){
        ensureProjectFile(".gitignore");

        var gitIgnorePath = validateProjectPath(".gitignore");
        var content = File.getContent(gitIgnorePath);
        var header = "# Auto generated by Spilehx lib";
        var entry = Path.normalize(path);
        var hasHeader = false;
        var hasEntry = false;

        for (line in content.split("\n")) {
            var trimmedLine = StringTools.rtrim(line);
            if (trimmedLine == header) hasHeader = true;
            if (trimmedLine == entry) hasEntry = true;
        }

        if (hasHeader && hasEntry) return;

        var updatedContent = content;

        if (!hasHeader) {
            var separator = updatedContent.length == 0 || StringTools.endsWith(updatedContent, "\n") ? "" : "\n";
            updatedContent += separator + header + "\n";
        }

        if (!hasEntry) {
            var separator = updatedContent.length == 0 || StringTools.endsWith(updatedContent, "\n") ? "" : "\n";
            updatedContent += separator + entry + "\n";
        }

        File.saveContent(gitIgnorePath, updatedContent);
    }

	#end
}
